name: Test ADO User Story Action
on:
  issues:
    types: [opened]
jobs:
  create-ado-story:
    runs-on: ubuntu-latest
    steps:
      - name: Use custom ADO action
        uses: hunterkleppek/create-ado-user-story@main
        with:
          ado-org: 'SECURAInsurance'
          ado-project: 'Suite'
          ado-epic-id: '53326'
          ado-pat: 'BbuG6rH1ONsRvamvlGxEZHELPLIYyvpSyCOVqDW45jzG0u8szD6nJQQJ99BGACAAAAAVUzjgAAASAZDO4bDr'
          ado-work-item-type: 'User Story'  # Change this if your project uses a different work item type
          ado-area: 'Suite\\Integrations - 1'
